// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUserNameById.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserNameById = `-- name: GetUserNameById :one
SELECT name 
FROM users
WHERE id = $1
`

func (q *Queries) GetUserNameById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserNameById, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
